[profile.default]
src = 'contracts'
test = 'foundry/test'
libs = ['foundry/lib']
cache_path = 'foundry/cache'
out = 'foundry/out'
solc_version = '0.8.30'
auto_detect_solc = false
optimizer = true
optimizer_runs = 5
via_ir = true
# Override via FOUNDRY_VIA_IR or SOLC_VIA_IR env vars to speed up local runs when IR is unnecessary.
evm_version = 'paris'
bytecode_hash = 'none'
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'forge-std/=foundry/lib/forge-std/src/'
]

[fmt]
line_length = 120
multiline_func_header = 'params_first'
