[profile.default]
src = 'contracts'
test = 'foundry/test'
libs = ['foundry/lib']
cache_path = 'foundry/cache'
out = 'foundry/out'
solc_version = '0.8.25'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'forge-std/=foundry/lib/forge-std/src/'
]

[fmt]
line_length = 120
multiline_func_header = 'params_first'
